version: 2

sources:
  - name: bronze
    database: OLIST_DB
    schema: BRONZE

    tables:
      - name: raw_customers
      - name: raw_geolocation
      - name: raw_orders
      - name: raw_order_items
      - name: raw_order_payments
      - name: raw_order_reviews
      - name: raw_products
      - name: raw_sellers
      - name: raw_product_category_translation