version: 2

models:
  - name: stg_customers
    description: Customer staging model

    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: Orders staging model

    columns:
      - name: order_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id

  - name: stg_order_items
    description: Order items staging model

    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id

      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id

      - name: seller_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_sellers')
              field: seller_id

  - name: stg_products
    description: Products staging model

    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_sellers
    description: Sellers staging model

    columns:
      - name: seller_id
        tests:
          - unique
          - not_null